---
# Install Dx-toolkit

# - name: Load DNAnexus repo signing key
#   apt_key: url=https://wiki.dnanexus.com/images/files/ubuntu-signing-key.gpg

# - name: Add dx-toolkit ppa
#   apt_repository: repo="{{item}}"
#   with_items:
#   - "deb http://dnanexus-apt-prod.s3.amazonaws.com/ubuntu trusty/amd64/"
#   - "deb http://dnanexus-apt-prod.s3.amazonaws.com/ubuntu trusty/all/"

# - name: Update apt
#   apt: update_cache=yes

# - name: Install dx-toolkit
#   apt: pkg=dx-toolkit state=present

- name: Get DX tarball
  unarchive: src=https://wiki.dnanexus.com/images/files/dx-toolkit-current-ubuntu-14.04-amd64.tar.gz dest=/opt copy=no

# http://stackoverflow.com/questions/22256884/not-possible-to-source-bashrc-with-ansible
- name: check dx version
  shell: source /opt/dx-toolkit/environment  && dx --version
  args:
    executable: /bin/bash
  register: dx_version

- name: Print dx version
  debug:
    msg: "Dx-toolkit Version {{ dx_version.stdout }}"

# Install Upload Agent
- name: Create folder to house upload agent
  file: path=/opt/dnanexus-upload-agent state=directory mode=0755

- name: Download and unzip UA tarball
  unarchive: src=https://wiki.dnanexus.com/images/files/dnanexus-upload-agent-current-linux.tar.gz dest=/opt/dnanexus-upload-agent copy=no

- name: Move ua executable to un-versioned folder location for ease of reference
  shell: mv /opt/dnanexus-upload-agent/*/* /opt/dnanexus-upload-agent/

- name: Check installed UA version
  command: ua --version
  environment:
    PATH: /opt/dnanexus-upload-agent:{{ ansible_env.PATH }}
  register: ua_version

- name: Print installed UA version
  debug:
    msg: "Upload agent Version {{ ua_version.stdout }}"

# # Set up CRON job for monitoring
# -
